name: .NET Core Build with Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      config: 'Release'
      
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
      
      # restore dependencies  
    - name: Install dependencies
      run: dotnet restore
      working-directory: tests
      
      # build project
    - name: Build
      run: dotnet build --configuration $config --no-restore
      working-directory: tests
      
    - name: set pr build number (if pr)
      id: PRNUMBER
      if: ${{ github.event_name == 'pull_request' }}
      uses: kkak10/pr-number-action@v1.3
      
      # run tests with built project
    - name: Test PR
      run: dotnet test --no-restore --no-build --configuration $config --logger:"liquid.md;LogFileName=${{github.workspace}}/TestReport.${{github.run_number}}.md;Title=${{github.repository}}/TestReport.${{github.run_number}};"
      working-directory: tests
      
      # upload report as build artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      if: ${{always()}}
      with:
        name: ${{github.repository_owner}} Test Run ${{github.run_number}}
        path: tests/${{github.workspace}}/BIS305TestReport.${{github.run_number}}.md
      
      # add report as PR comment (if PR)
    - name: comment PR
      uses: machine-learning-apps/pr-comment@master
      if: ${{ github.event_name == 'pull_request' }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        path: tests/TestReport.${{github.run_number}}.md"
